export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const AUTH_ERROR = 'AUTH_ERRORR';
export const CLEAR_ERRORS = 'CLEAR_ERRORRS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';


export const NEW_EXERCISE_SUCCESS = 'NEW_EXERCISE_SUCCESS';
export const GET_EXERCISES_SUCCESS = 'GET_EXERCISES_SUCCESS';
export const EXERCISE_FAIL = 'EXERCISE_FAIL';
export const GET_EXERCISE_BY_ID = 'GET_EXERCISE_BY_ID';
export const CLEAR_EXERCISES = 'CLEAR_EXERCISES';
export const CLEAR_CURRENT_EXERCISE = 'CLEAR_CURRENT_EXERCISE';